# -*- coding: utf-8 -*-
# ====================================== #
# @Author  : Yanbo Han
# @Email   : yanbohan98@gmail.com
# @File    : input.py
# ALL RIGHTS ARE RESERVED UNLESS STATED.
# ====================================== #
import pathlib

# Established based on OUT.ABACUS/INPUT
# Note: maximum of key is 30, if more, modify last line "{key: <30}"
AbacusInputKeyDict = {
    # Parameters (1.General)
    "general": {
        "suffix",
        "latname",
        "atom_file",
        "kpoint_file",
        "pseudo_dir",
        "pseudo_type",
        "dft_functional",
        "calculation",
        "ntype",
        "nspin",
        "nbands",
        "nbands_sto",
        "nbands_istate",
        "nche_sto",
        "symmetry",
        "nelec"},
    # Parameters (2.PW)
    "pw": {
        "ecutwfc",
        "diago_cg_maxiter",
        "diago_cg_prec",
        "ethr",
        "dr2",
        "start_wfc",
        "start_charge",
        "charge_extrap",
        "out_charge",
        "out_potential",
        "out_wf",
        "out_dos",
        "out_band",
        "restart_save",
        "restart_load",
        "read_file_dir",
        "nx",
        "ny",
        "nz"},
    # Parameters (3.Relaxation)
    "relaxation": {
        "ks_solver",
        "niter",
        "force_set",
        "nstep",
        "out_stru",
        "force_thr",
        "force_thr_ev",
        "force_thr_ev2",
        "stress_thr",
        "press1",
        "press2",
        "press3",
        "bfgs_w1",
        "bfgs_w2",
        "trust_radius_max",
        "trust_radius_min",
        "trust_radius_ini",
        "stress",
        "fixed_axes",
        "move_method",
        "out_level",
        "out_dm",
        "out_descriptor",
        "lmax_descriptor"},
    # Parameters (4.LCAO)
    "lcao": {
        "basis_type",
        "new_dm",
        "search_radius",
        "search_pbc",
        "lcao_ecut",
        "lcao_dk",
        "lcao_dr",
        "lcao_rmax",
        "out_hs",
        "out_lowf",
        "bx",
        "by",
        "bz"},
    # Parameters (5.Smearing)
    "smearing": {
        "smearing",
        "sigma"},
    # Parameters (6.Charge Mixing)
    "charge_mixing": {
        "mixing_type",
        "mixing_beta",
        "mixing_ndim",
        "mixing_gg0"},
    # Parameters (7.DOS)
    "dos": {
        "dos_emin_ev",
        "dos_emax_ev",
        "dos_edelta_ev",
        "dos_sigma"},
    # Parameters (8.Technique)
    "technique": {
        "gamma_only",
        "diago_proc",
        "npool",
        "mem_saver",
        "printe"},
    # Parameters (9.SIAO)
    "siao": {
        "selinv_npole",
        "selinv_temp",
        "selinv_gap",
        "selinv_deltae",
        "selinv_mu",
        "selinv_threshold",
        "selinv_niter"},
    # Parameters (10.Molecular dynamics)
    "molecular_dynamics": {
        "md_mdtype",
        "md_dt",
        "mnhc",
        "md_qmass",
        "md_tfirst",
        "md_tlast",
        "md_dumpmdfred",
        "md_mdoutpath",
        "md_rstmd",
        "md_fixtemperature",
        "md_ediff",
        "md_ediffg",
        "NVT_tau",
        "NVT_control"},
    # Parameters (11.Efield)
    "efield": {
        "efield",
        "edir",
        "emaxpos",
        "eopreg",
        "eamp",
        "eamp_v"},
    # Parameters (12.Test)
    "test": {
        "out_alllog",
        "nurse",
        "colour",
        "t_in_h",
        "vl_in_h",
        "vnl_in_h",
        "test_force",
        "test_stress"},
    # Parameters (13.Other Methods)
    "other_methods": {
        "mlwf_flag",
        "opt_epsilon2",
        "opt_nbands"},
    # Parameters (14.VdW Correction)
    "vdw_correction": {
        "vdw_method",
        "vdw_s6",
        "vdw_s8",
        "vdw_a1",
        "vdw_a2",
        "vdw_d",
        "vdw_abc",
        "vdw_C6_file",
        "vdw_C6_unit",
        "vdw_R0_file",
        "vdw_R0_unit",
        "vdw_model",
        "vdw_radius",
        "vdw_radius_unit",
        "vdw_cn_thr",
        "vdw_cn_thr_unit",
        "vdw_period"},
    # Parameters (15.spectrum)
    "spectrum": {
        "spectral_type",
        "spectral_method",
        "kernel_type",
        "eels_method",
        "absorption_method",
        "system",
        "eta",
        "domega",
        "nomega",
        "ecut_chi",
        "q_start",
        "q_direction",
        "nq",
        "out_epsilon",
        "out_chi",
        "out_chi0",
        "fermi_level",
        "coulomb_cutoff",
        "kmesh_interpolation",
        "qcar",
        "ocp",
        "ocp_set",
        "lcao_box",
        "mulliken",
        "intrasmear",
        "shift",
        "metalcalc",
        "eps_degauss",
        "noncolin",
        "lspinorb"},
    # Parameters (17.exx)
    "exx": {
        "exx_hybrid_type",
        "exx_hybrid_alpha",
        "exx_hse_omega",
        "exx_separate_loop",
        "exx_hybrid_step",
        "exx_lambda",
        "exx_pca_threshold",
        "exx_c_threshold",
        "exx_v_threshold",
        "exx_dm_threshold",
        "exx_schwarz_threshold",
        "exx_cauchy_threshold",
        "exx_ccp_threshold",
        "exx_ccp_rmesh_times",
        "exx_distribute_type",
        "exx_opt_orb_lmax",
        "exx_opt_orb_ecut",
        "exx_opt_orb_tolerenc"},
    # Parameters (17.tddft)
    "tddft": {
        "td_dr2",
        "td_dt",
        "td_force_dt",
        "td_val_elec_01",
        "td_val_elec_02",
        "td_val_elec_03",
        "td_vext",
        "td_vext_dire",
        "td_timescale",
        "td_vexttype",
        "td_vextout",
        "td_dipoleout"},
    # Parameters (18.berry_wannier)
    "berry_wannier": {
        "berry_phase",
        "gdir",
        "towannier90",
        "nnkpfile",
        "wannier_spin"},
}
BlockComments = {
    'general': '#Parameters (1.General)',
    'pw': '#Parameters (2.PW)',
    'relaxation': '#Parameters (3.Relaxation)',
    'lcao': '#Parameters (4.LCAO)',
    'smearing': '#Parameters (5.Smearing)',
    'charge_mixing': '#Parameters (6.Charge Mixing)',
    'dos': '#Parameters (7.DOS)',
    'technique': '#Parameters (8.Technique)',
    'siao': '#Parameters (9.SIAO)',
    'molecular_dynamics': '#Parameters (10.Molecular dynamics)',
    'efield': '#Parameters (11.Efield)',
    'test': '#Parameters (12.Test)',
    'other_methods': '#Parameters (13.Other Methods)',
    'vdw_correction': '#Parameters (14.VdW Correction)',
    'spectrum': '#Parameters (15.spectrum)',
    'exx': '#Parameters (17.exx)',
    'tddft': '#Parameters (17.tddft)',
    'berry_wannier': '#Parameters (18.berry_wannier)',
}
AbacusInputBlock = {
    # Parameters (1.General)
    'latname': 'general',
    'nbands_istate': 'general',
    'calculation': 'general',
    'atom_file': 'general',
    'nbands': 'general',
    'pseudo_dir': 'general',
    'ntype': 'general',
    'nelec': 'general',
    'nche_sto': 'general',
    'pseudo_type': 'general',
    'dft_functional': 'general',
    'kpoint_file': 'general',
    'nspin': 'general',
    'nbands_sto': 'general',
    'symmetry': 'general',
    'suffix': 'general',
    # Parameters (2.PW)
    'out_potential': 'pw',
    'dr2': 'pw',
    'nx': 'pw',
    'nz': 'pw',
    'charge_extrap': 'pw',
    'diago_cg_prec': 'pw',
    'start_charge': 'pw',
    'out_wf': 'pw',
    'ecutwfc': 'pw',
    'out_band': 'pw',
    'out_dos': 'pw',
    'ny': 'pw',
    'out_charge': 'pw',
    'ethr': 'pw',
    'restart_save': 'pw',
    'read_file_dir': 'pw',
    'restart_load': 'pw',
    'diago_cg_maxiter': 'pw',
    'start_wfc': 'pw',
    # Parameters (3.Relaxation)
    'press3': 'relaxation',
    'press1': 'relaxation',
    'nstep': 'relaxation',
    'force_thr_ev2': 'relaxation',
    'out_stru': 'relaxation',
    'out_level': 'relaxation',
    'move_method': 'relaxation',
    'trust_radius_min': 'relaxation',
    'niter': 'relaxation',
    'bfgs_w2': 'relaxation',
    'force_set': 'relaxation',
    'out_dm': 'relaxation',
    'bfgs_w1': 'relaxation',
    'force_thr': 'relaxation',
    'stress': 'relaxation',
    'lmax_descriptor': 'relaxation',
    'press2': 'relaxation',
    'ks_solver': 'relaxation',
    'force_thr_ev': 'relaxation',
    'stress_thr': 'relaxation',
    'out_descriptor': 'relaxation',
    'trust_radius_ini': 'relaxation',
    'trust_radius_max': 'relaxation',
    'fixed_axes': 'relaxation',
    # Parameters (4.LCAO)
    'lcao_dk': 'lcao',
    'bx': 'lcao',
    'search_radius': 'lcao',
    'by': 'lcao',
    'bz': 'lcao',
    'new_dm': 'lcao',
    'basis_type': 'lcao',
    'lcao_ecut': 'lcao',
    'lcao_dr': 'lcao',
    'lcao_rmax': 'lcao',
    'out_hs': 'lcao',
    'out_lowf': 'lcao',
    'search_pbc': 'lcao',
    # Parameters (5.Smearing)
    'smearing': 'smearing',
    'sigma': 'smearing',
    # Parameters (6.Charge Mixing)
    'mixing_gg0': 'charge_mixing',
    'mixing_type': 'charge_mixing',
    'mixing_ndim': 'charge_mixing',
    'mixing_beta': 'charge_mixing',
    # Parameters (7.DOS)
    'dos_edelta_ev': 'dos',
    'dos_emax_ev': 'dos',
    'dos_sigma': 'dos',
    'dos_emin_ev': 'dos',
    # Parameters (8.Technique)
    'diago_proc': 'technique',
    'npool': 'technique',
    'mem_saver': 'technique',
    'printe': 'technique',
    'gamma_only': 'technique',
    # Parameters (9.SIAO)
    'selinv_niter': 'siao',
    'selinv_threshold': 'siao',
    'selinv_mu': 'siao',
    'selinv_temp': 'siao',
    'selinv_gap': 'siao',
    'selinv_npole': 'siao',
    'selinv_deltae': 'siao',
    # Parameters (10.Molecular dynamics)
    'NVT_tau': 'molecular_dynamics',
    'md_dumpmdfred': 'molecular_dynamics',
    'md_fixtemperature': 'molecular_dynamics',
    'mnhc': 'molecular_dynamics',
    'md_qmass': 'molecular_dynamics',
    'md_tlast': 'molecular_dynamics',
    'md_mdoutpath': 'molecular_dynamics',
    'md_dt': 'molecular_dynamics',
    'md_mdtype': 'molecular_dynamics',
    'md_tfirst': 'molecular_dynamics',
    'NVT_control': 'molecular_dynamics',
    'md_ediffg': 'molecular_dynamics',
    'md_rstmd': 'molecular_dynamics',
    'md_ediff': 'molecular_dynamics',
    # Parameters (11.Efield)
    'eamp_v': 'efield',
    'emaxpos': 'efield',
    'efield': 'efield',
    'eamp': 'efield',
    'eopreg': 'efield',
    'edir': 'efield',
    # Parameters (12.Test)
    'test_stress': 'test',
    't_in_h': 'test',
    'nurse': 'test',
    'test_force': 'test',
    'out_alllog': 'test',
    'colour': 'test',
    'vl_in_h': 'test',
    'vnl_in_h': 'test',
    # Parameters (13.Other Methods)
    'mlwf_flag': 'other_methods',
    'opt_nbands': 'other_methods',
    'opt_epsilon2': 'other_methods',
    # Parameters (14.VdW Correction)
    'vdw_s8': 'vdw_correction',
    'vdw_radius': 'vdw_correction',
    'vdw_a1': 'vdw_correction',
    'vdw_R0_file': 'vdw_correction',
    'vdw_R0_unit': 'vdw_correction',
    'vdw_s6': 'vdw_correction',
    'vdw_C6_file': 'vdw_correction',
    'vdw_method': 'vdw_correction',
    'vdw_radius_unit': 'vdw_correction',
    'vdw_cn_thr_unit': 'vdw_correction',
    'vdw_cn_thr': 'vdw_correction',
    'vdw_C6_unit': 'vdw_correction',
    'vdw_a2': 'vdw_correction',
    'vdw_d': 'vdw_correction',
    'vdw_period': 'vdw_correction',
    'vdw_abc': 'vdw_correction',
    'vdw_model': 'vdw_correction',
    # Parameters (15.spectrum)
    'eps_degauss': 'spectrum',
    'lcao_box': 'spectrum',
    'out_chi': 'spectrum',
    'eta': 'spectrum',
    'nq': 'spectrum',
    'domega': 'spectrum',
    'nomega': 'spectrum',
    'spectral_type': 'spectrum',
    'kmesh_interpolation': 'spectrum',
    'eels_method': 'spectrum',
    'out_chi0': 'spectrum',
    'lspinorb': 'spectrum',
    'ocp': 'spectrum',
    'intrasmear': 'spectrum',
    'noncolin': 'spectrum',
    'coulomb_cutoff': 'spectrum',
    'qcar': 'spectrum',
    'q_direction': 'spectrum',
    'out_epsilon': 'spectrum',
    'ocp_set': 'spectrum',
    'absorption_method': 'spectrum',
    'q_start': 'spectrum',
    'metalcalc': 'spectrum',
    'ecut_chi': 'spectrum',
    'fermi_level': 'spectrum',
    'mulliken': 'spectrum',
    'kernel_type': 'spectrum',
    'shift': 'spectrum',
    'system': 'spectrum',
    'spectral_method': 'spectrum',
    # Parameters (17.exx)
    'exx_cauchy_threshold': 'exx',
    'exx_lambda': 'exx',
    'exx_c_threshold': 'exx',
    'exx_separate_loop': 'exx',
    'exx_schwarz_threshold': 'exx',
    'exx_ccp_rmesh_times': 'exx',
    'exx_hse_omega': 'exx',
    'exx_distribute_type': 'exx',
    'exx_opt_orb_lmax': 'exx',
    'exx_hybrid_alpha': 'exx',
    'exx_opt_orb_tolerenc': 'exx',
    'exx_dm_threshold': 'exx',
    'exx_hybrid_type': 'exx',
    'exx_hybrid_step': 'exx',
    'exx_pca_threshold': 'exx',
    'exx_opt_orb_ecut': 'exx',
    'exx_v_threshold': 'exx',
    'exx_ccp_threshold': 'exx',
    # Parameters (17.tddft)
    'td_vext_dire': 'tddft',
    'td_vextout': 'tddft',
    'td_dt': 'tddft',
    'td_val_elec_03': 'tddft',
    'td_vexttype': 'tddft',
    'td_dipoleout': 'tddft',
    'td_dr2': 'tddft',
    'td_val_elec_01': 'tddft',
    'td_vext': 'tddft',
    'td_timescale': 'tddft',
    'td_val_elec_02': 'tddft',
    'td_force_dt': 'tddft',
    # Parameters (18.berry_wannier)
    'berry_phase': 'berry_wannier',
    'wannier_spin': 'berry_wannier',
    'gdir': 'berry_wannier',
    'nnkpfile': 'berry_wannier',
    'towannier90': 'berry_wannier'
}


def write_abacus_input(
        task_root: str,
        input_para_dict: dict
):
    all_input_keys = input_para_dict.keys()
    input_blocks = set()
    for key in all_input_keys:
        try:
            input_blocks.add(AbacusInputBlock[key])
        except KeyError:
            raise KeyError(f"Invalid Input Key for ABACUS: {key}")

    with open(pathlib.Path(task_root) / "INPUT", "w") as f:
        print("INPUT_PARAMETERS", file=f)
        for block in input_blocks:
            print(BlockComments[block], file=f)
            for key in AbacusInputKeyDict[block]:
                if key in all_input_keys:
                    print(f"{key: <30}{input_para_dict[key]}", file=f)

